spring:
  profiles:
    active: local
  
  # Use H2 in-memory database for local testing
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # Disable Redis for local testing
  redis:
    enabled: false
  
  # Use embedded Kafka for local testing
  kafka:
    enabled: false

# Disable external services for local testing
elasticsearch:
  enabled: false

influxdb:
  enabled: false

# Enable test data generation
test-data:
  enabled: true
  generate-on-startup: true
  log-count: 1000

logging:
  level:
    com.loganalyzer: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/application.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Local testing configuration
local-testing:
  mock-services: true
  generate-sample-data: true
  enable-cors: true

server:
  port: 8080
  servlet:
    context-path: /api/v1

# CORS configuration for local development
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://127.0.0.1:3000
  allowed-methods: 
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true
